site_name: Product Purchasing Hub Docs
site_description: 'Documentation for https://github.com/Redon-Tech/Roblox-Purchasing-Hub/'
site_author: 'Redon Tech'
docs_dir: docs/
repo_name: 'Redon-Tech/Roblox-Purchasing-Hub'
repo_url: 'https://github.com/Redon-Tech/Roblox-Purchasing-Hub/'
nav:
    - Home: index.md
    - Setup:
      - Basic Setup: installation/setup.md
      - Bot & API Setup: installation/bot-api-setup.md
    - API:
      - Reference: api-reference.md
theme:
  features:
    - navigation.instant
  name: 'material'
  palette:
    scheme: slate
    primary: black
    accent: red
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true