site_name: Product Purchasing Hub Docs
site_description: 'Documentation for https://github.com/Redon-Tech/Roblox-Purchasing-Hub/'
site_author: 'Redon Tech'
docs_dir: docs/
repo_name: 'Redon-Tech/Roblox-Purchasing-Hub'
repo_url: 'https://github.com/Redon-Tech/Roblox-Purchasing-Hub/'
nav:
    - Home: index.md
theme:
  name: 'material'
  palette:
    scheme: slate
    primary: black
    accent: red
